// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChIA_ae6fTDWWqbX6RmGCMQLap4hSnwjQ',
    appId: '1:655483694502:web:09fe9e06f5e4f939e33367',
    messagingSenderId: '655483694502',
    projectId: 'congty-14d9f',
    authDomain: 'congty-14d9f.firebaseapp.com',
    storageBucket: 'congty-14d9f.appspot.com',
    measurementId: 'G-5WR9GCFGNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADXdqPpE3gXPpwHKCTbWRVLmxIekOWalk',
    appId: '1:655483694502:android:3d2c7d5e24505c76e33367',
    messagingSenderId: '655483694502',
    projectId: 'congty-14d9f',
    storageBucket: 'congty-14d9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxBkP6wu763DqNUi_MdraXHe7SPNktFTQ',
    appId: '1:655483694502:ios:7702240e20e0c449e33367',
    messagingSenderId: '655483694502',
    projectId: 'congty-14d9f',
    storageBucket: 'congty-14d9f.appspot.com',
    iosBundleId: 'com.example.tuhocCty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxBkP6wu763DqNUi_MdraXHe7SPNktFTQ',
    appId: '1:655483694502:ios:f5b6bc1bced68992e33367',
    messagingSenderId: '655483694502',
    projectId: 'congty-14d9f',
    storageBucket: 'congty-14d9f.appspot.com',
    iosBundleId: 'com.example.tuhocCty.RunnerTests',
  );
}
